db:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=pass
  volumes_from:
    - storage
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
storage:
  image: busybox
  volumes:
    - /var/lib/mysql
