# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4588bc9145a3606df1399279d35078e6867419ce3cc54dee6f9e3ffd7e6af2d755eb4b759bffdbcc3d1c98479d328bf965e57595346f7cd8bf2afcfb2e66b4c2

test:
  secret_key_base: 665e09c2c5e25b65560f6f5cd99e0f8295e8ff8471fec21acfe5344d5b834d0a5952c69ee038df23a14ed24ab52f42cbc3cf3f9fe1f8b2329e2966d476260a93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
