web:
  image: nginx:latest
  links:
    - api:api
  ports:
    - "80:80"
  volumes:
    - ./web:/etc/nginx/conf.d
  volumes_from:
    - api
api:
  build: ./api
  command: bundle exec ruby app.rb -o 0.0.0.0
  expose:
    - "4567"
  volumes:
    - ./api:/app
  links:
    - redis
redis:
  image: redis:latest
